### ISSUE TITLE
Unrecognized options should blow up

### ISSUE THREAD

**Issue by grosser** [spox/bogo-cli#5]
same as optparse and all other commandline tools do

```
fn destroy hostgroup-xyz -f xyz.rb
ERROR: Miasma::Error::ApiError::RequestError: Bad Request
```

... great ... now I'll just guess that that means it tried to destroy a stack called '-f' :)

@chrisroberts

**Comment by chrisroberts** [comment]
Addressed in #6 and is shipped in the v0.2.0 release. Thanks!
